import {createRoute} from "@wisdom-serve/serve"
export default createRoute({
    routes:[
        {
            path:"/asd",
            controller(){
                console.log(1)
            },
            children:[
                {
                    path:"1",
                    controller(){
                        console.log(2)
                    },
                    children:[
                        {
                            path:"2",
                            controller(){
                                console.log(3)
                            },
                        }
                    ]
                },
                {
                    path:"3",
                    controller(){
                        console.log(4)
                    },
                }
            ]
        },
        {
            path:"sda",
            controller() {
                console.log(5)
            }
        },
        {
            path:"4",
            controller(){
                console.log(6)
            },
            children:[
                {
                    path:"5",
                    controller(){
                        console.log(7)
                    },
                }
            ]
        },
    ]
});
